2025-07-27 22:31:32 | INFO | model_worker | args: Namespace(host='0.0.0.0', port=40000, worker_address='http://localhost:40000', controller_address='http://localhost:10000', model_path='C:\\Users\\48108\\LLaVA\\checkpoints\\llava-1.5-7b-hf', model_base=None, model_name=None, device='cuda', multi_modal=False, limit_model_concurrency=5, stream_interval=1, no_register=False, load_8bit=False, load_4bit=False, use_flash_attn=False)
2025-07-27 22:31:32 | INFO | model_worker | Loading the model C:\Users\48108\LLaVA\checkpoints\llava-1.5-7b-hf on worker 1e7e31 ...
2025-07-27 22:31:32 | ERROR | stderr | Traceback (most recent call last):
2025-07-27 22:31:32 | ERROR | stderr |   File "C:\Users\48108\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
2025-07-27 22:31:32 | ERROR | stderr |     return _run_code(code, main_globals, None,
2025-07-27 22:31:32 | ERROR | stderr |   File "C:\Users\48108\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
2025-07-27 22:31:32 | ERROR | stderr |     exec(code, run_globals)
2025-07-27 22:31:32 | ERROR | stderr |   File "C:\Users\48108\LLaVA\llava\serve\model_worker.py", line 277, in <module>
2025-07-27 22:31:32 | ERROR | stderr |     worker = ModelWorker(args.controller_address,
2025-07-27 22:31:32 | ERROR | stderr |   File "C:\Users\48108\LLaVA\llava\serve\model_worker.py", line 65, in __init__
2025-07-27 22:31:32 | ERROR | stderr |     self.tokenizer, self.model, self.image_processor, self.context_len = load_pretrained_model(
2025-07-27 22:31:32 | ERROR | stderr |   File "C:\Users\48108\LLaVA\llava\model\builder.py", line 116, in load_pretrained_model
2025-07-27 22:31:32 | ERROR | stderr |     tokenizer = AutoTokenizer.from_pretrained(model_path, use_fast=False)
2025-07-27 22:31:32 | ERROR | stderr |   File "C:\Users\48108\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\models\auto\tokenization_auto.py", line 814, in from_pretrained
2025-07-27 22:31:32 | ERROR | stderr |     return tokenizer_class.from_pretrained(pretrained_model_name_or_path, *inputs, **kwargs)
2025-07-27 22:31:32 | ERROR | stderr |   File "C:\Users\48108\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\tokenization_utils_base.py", line 2029, in from_pretrained
2025-07-27 22:31:32 | ERROR | stderr |     return cls._from_pretrained(
2025-07-27 22:31:32 | ERROR | stderr |   File "C:\Users\48108\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\tokenization_utils_base.py", line 2261, in _from_pretrained
2025-07-27 22:31:32 | ERROR | stderr |     tokenizer = cls(*init_inputs, **init_kwargs)
2025-07-27 22:31:32 | ERROR | stderr |   File "C:\Users\48108\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\models\llama\tokenization_llama.py", line 178, in __init__
2025-07-27 22:31:32 | ERROR | stderr |     self.sp_model = self.get_spm_processor(kwargs.pop("from_slow", False))
2025-07-27 22:31:32 | ERROR | stderr |   File "C:\Users\48108\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\models\llama\tokenization_llama.py", line 208, in get_spm_processor
2025-07-27 22:31:32 | ERROR | stderr |     model_pb2 = import_protobuf(f"The new behaviour of {self.__class__.__name__} (with `self.legacy = False`)")
2025-07-27 22:31:32 | ERROR | stderr |   File "C:\Users\48108\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\convert_slow_tokenizer.py", line 43, in import_protobuf
2025-07-27 22:31:32 | ERROR | stderr |     raise ImportError(PROTOBUF_IMPORT_ERROR.format(error_message))
2025-07-27 22:31:32 | ERROR | stderr | ImportError:
2025-07-27 22:31:32 | ERROR | stderr | The new behaviour of LlamaTokenizer (with `self.legacy = False`) requires the protobuf library but it was not found in your environment. Checkout the instructions on the
2025-07-27 22:31:32 | ERROR | stderr | installation page of its repo: https://github.com/protocolbuffers/protobuf/tree/master/python#installation and follow the ones
2025-07-27 22:31:32 | ERROR | stderr | that match your environment. Please note that you may need to restart your runtime after installation.
2025-07-27 22:31:32 | ERROR | stderr | 
